const applicants = [
    {firstName: "Emily",
    lastName: "Readey",
    likes: 42,
    comments: 53,
    tags: []},
    {firstName: "Rohan",
    lastName: "Pahwa",
    likes: 21,
    comments: 51,
    tags: []},
    {firstName: "Yuki",
    lastName: "Peters",
    likes: 25,
    comments: 32,
    tags: []},
    {firstName: "Leo",
    lastName: "Au-Yeung",
    likes: 12,
    comments: 31,
    tags: []},
    {firstName: "Eunia",
    lastName: "Lee",
    likes: 14,
    comments: 29,
    tags: []}, 
]

export default applicants